app:
  message: message succesfuly sent
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: people.exchange
    routingkey: people.routingkey
server:
  port: 8081
